const LOGIN = "LOGIN";
const SIGNUP = "SIGNUP";
const LOGOUT = "LOGOUT";
const CURRENT_USER = "CURRENT_USER";
const IS_ADMIN = "IS_ADMIN";
const ALL_FILMS = "ALL_FILMS";
const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
const RATE_FILM = "RATE_FILM";
const ADD_COMMENT = "ADD_COMMENT";
const CURRENT_FILM = 'CURRENT_FILM';
const TOKEN = "TOKEN";
const FILM_RATING_USER = 'FILM_RATING_USER';
const ERROR = 'ERROR';
const ADD_FILM = "ADD_FILM";
const EDIT_FILM = "EDIT_FILM";
const DELETE_FILM = "DELETE_FILM";


export {
    LOGIN,
    SIGNUP,
    LOGOUT,
    ALL_FILMS,
    ADD_TO_FAVOURITES,
    REMOVE_FROM_FAVOURITES,
    RATE_FILM,
    ADD_COMMENT,
    ADD_FILM,
    EDIT_FILM,
    DELETE_FILM,
    CURRENT_FILM,
    CURRENT_USER,
    FILM_RATING_USER,
    IS_ADMIN,
    TOKEN,
    ERROR
}