const LOGIN = "LOGIN";
const SIGNUP = "SIGNUP";
const LOGOUT = "LOGOUT";

const ALL_FILMS = "ALL_FILMS";
const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
const RATE_FILM = "RATE_FILM";
const ADD_COMMENT = "ADD_COMMENT";
const CURRENT_FILM = 'CURRENT_FILM';

const ADD_FILM = "ADD_FILM";
const EDIT_FILM = "EDIT_FILM";
const DELETE_FILM = "DELETE_FILM";


export {
    LOGIN,
    SIGNUP,
    LOGOUT,
    ALL_FILMS,
    ADD_TO_FAVOURITES,
    REMOVE_FROM_FAVOURITES,
    RATE_FILM,
    ADD_COMMENT,
    ADD_FILM,
    EDIT_FILM,
    DELETE_FILM,
    CURRENT_FILM 
}